# Use the official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn

# Copy the necessary application code to the working directory
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript code
RUN yarn build

# Expose the port that the server will run on
EXPOSE 3000

# Start the server
CMD ["yarn", "run-solana-server"]